name: doab_records
favicon: null
layout_spectrum: 0.5983824653085321
typography_spectrum: 0.8578796978108585
title: doab records
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.73450647899881
  lightness: 0.21819108561612666
  saturation: 0.08528692554682493
  rhythmicContrast: 0.6831691635306925
purpose: []
